name: Update commit.toml
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate commit.toml
        shell: nix shell nixpkgs#nushell --command bash {0}
        run: |
          nu scripts/generate-toml.nu

      - name: Test if buildable
        run: |
          nix build -L .#cwc

      - name: Check for changes
        id: status
        run: |
          changes="$(git status --porcelain)"
          echo "changes=${#changes}" >> $GITHUB_OUTPUT

      - name: Push changes
        if: ${{ steps.status.outputs.changes != '0' }}
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add commit.toml
          git commit -m "bump: update to latest commit"
          git push
